In [1]:
import pandas as pd

In [3]:
from sklearn.preprocessing import LabelEncoder
class_names = ["Above", "Below", "Whole Plant", "Other"]
labelenc = LabelEncoder().fit(class_names)
labelenc.transform(class_names).tolist()

[0, 1, 3, 2]

In [2]:
angio_rnafile = "../data/backup/Angiosperm_RNAseq_clean.csv"
angio_metafile = "../data/backup/Angiosperm_metadata_clean.csv"

angiorna = pd.read_csv(angio_rnafile)
angiorna.head(3)

,SampleID,AT1G01020,AT1G01040,AT1G01060,AT1G01090,AT1G01160,AT1G01190,AT1G01220,AT1G01225,AT1G01230,...,AT5G67220,AT5G67270,AT5G67320,AT5G67370,AT5G67390,AT5G67530,AT5G67550,AT5G67570,AT5G67590,AT5G67620
0,SRR1598911,10.637346,11.478871,10.732734,55.891862,33.988995,6.872655,7.054929,4.958908,70.512275,...,11.513462,18.716154,196.483225,29.421445,37.851169,5.871045,4.132813,4.751289,98.171942,3.092170
1,SRR1598912,2.936071,3.835814,4.383961,31.167773,17.302222,8.027402,6.130395,3.833271,21.472789,...,18.289706,35.480156,59.862219,32.420857,55.739565,2.764059,5.731131,5.946588,186.146673,1.149794
2,SRR1598913,7.392834,5.339042,12.098516,47.056837,19.742165,4.928601,9.425292,7.289562,30.790188,...,13.308414,54.701747,77.902594,1.195359,13.310283,2.858254,9.005569,1.934694,217.819931,7.862892

In [3]:
angiometa = pd.read_csv(angio_metafile)
angiometa.head(3)

     SampleID        family  tissue   stress AboveBelow VegetativeRepro
0  SRR1598911  Amaranthacea  flower  healthy      Above    Reproductive
1  SRR1598912  Amaranthacea    leaf  healthy      Above      Vegetative
2  SRR1598913  Amaranthacea    root  healthy      Below      Vegetative

In [5]:
angiometa["AboveBelow"].value_counts()

Above         1787
Below          482
WholePlant     321
Other           81
Name: AboveBelow, dtype: int64

In [ ]:
print(angiorna.shape, angiometa.shape)
angiodata = pd.merge(angiometa, angiorna, how="left", on="SampleID")
print(angiodata.shape)
angiodata.head(3)

In [ ]:
angiodata.to_csv("../data/Angiosperm_data_clean.csv", index=False)